version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    expose:
      - "${FASTAPI_PORT}"

  nginx:
    image: nginx:1.25.4
    volumes:
      - ./frontend/:/usr/share/nginx/html:ro
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/site.conf:/etc/nginx/conf.d/site.conf:ro
    depends_on:
      - app
    ports:
      - '80:80'