version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    expose:
      - "${FASTAPI_PORT}"

  nginx:
    image: nginx:latest
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - app
